### ISSUE TITLE
Connect to server

### ISSUE THREAD

**Issue by Al3ksand3r-dev88** [Puttzer/AirBean-Speedy-Unicorns#20]
When making a new order, connection to server is refused. When I look in the file structure I see "datamenu" and I guess its the backend part. When I try to run "node app" it doesn't work because there is no app.js file in the datamenu folder. Try and restructe the files and make the server connect to vue.

**Comment by Puttzer** [comment]
You can go around it by navigating in the terminal to the api folder then,

`npm i`

`node app`

Is that solution an incorrect one?

But w'll get on it!

**Comment by Puttzer** [comment]
Datamenu isnt the backend
api was lmao

**Comment by Puttzer** [comment]
Doing this turns out to be quite the extensive redo of the whole project due to too much being hard coded from the beginning and requires more time than there is.  

Unfortunatley i will have to close this without a fix
