### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by Al3ksand3r-dev88** [Puttzer/AirBean-Speedy-Unicorns#22]
File structure is good but there could be some minor changes to it for example the datamenu could be named "server" since it's the backend part of the project. From the server folder you could make the connection to the frontend. The frontend part of the project could be inside of a folder called "client" and in that way it's easier to differantiate between the backend and the frontend.

**Comment by Puttzer** [comment]
Datamenu is not the backend, its located in the src/api/ folder
